services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8000:8000" # Единый порт для всего фронтенда
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SERVICES_URLS: ${SERVICES_URLS}
    networks:
      - saas_network
    restart: unless-stopped
networks:
  saas_network:
    driver: bridge
    external: true